config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#index'
  get 'static_pages/index'
  get 'items/index'
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :items
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
   

end

app/models/item.rb
class Item < ActiveRecord::Base
    validates :title, presence: true, length: { minimum: 5 }
    has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ":style/missing.png"
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :subtitle, :ean_code, :description, :synopsis, :creator, :rating, :genres, :sold_by, :features, :format, :retail_price, :warranty, :date_of_purchase, :length, :width, :height, :amazon_link, :country, :image)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item, :html => { :multipart => true })  do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br>
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :ean_code %><br>
    <%= f.text_field :ean_code %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :synopsis %><br>
    <%= f.text_area :synopsis %>
  </div>
  <div class="field">
    <%= f.label :creator %><br>
    <%= f.text_field :creator %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :genres %><br>
    <%= f.text_field :genres %>
  </div>
  <div class="field">
    <%= f.label :sold_by %><br>
    <%= f.text_field :sold_by %>
  </div>
  <div class="field">
    <%= f.label :features %><br>
    <%= f.text_area :features %>
  </div>
  <div class="field">
    <%= f.label :format %><br>
    <%= f.text_field :format %>
  </div>
  <div class="field">
    <%= f.label :retail_price %><br>
    <%= f.text_field :retail_price %>
  </div>
  <div class="field">
    <%= f.label :warranty %><br>
    <%= f.text_field :warranty %>
  </div>
  <div class="field">
    <%= f.label :date_of_purchase %><br>
    <%= f.date_select :date_of_purchase %>
  </div>
  <div class="field">
    <%= f.label :length %><br>
    <%= f.text_field :length %>
  </div>
  <div class="field">
    <%= f.label :width %><br>
    <%= f.text_field :width %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :amazon_link %><br>
    <%= f.text_field :amazon_link %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= image_tag @item.image.url(:thumb) %>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Subtitle</th>
      <th>Ean code</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.subtitle %></td>
        <td><%= item.ean_code %></td>

        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @item.subtitle %>
</p>

<p>
  <strong>Ean code:</strong>
  <%= @item.ean_code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Synopsis:</strong>
  <%= @item.synopsis %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @item.creator %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @item.rating %>
</p>

<p>
  <strong>Genres:</strong>
  <%= @item.genres %>
</p>

<p>
  <strong>Sold by:</strong>
  <%= @item.sold_by %>
</p>

<p>
  <strong>Features:</strong>
  <%= @item.features %>
</p>

<p>
  <strong>Format:</strong>
  <%= @item.format %>
</p>

<p>
  <strong>Retail price:</strong>
  <%= @item.retail_price %>
</p>

<p>
  <strong>Warranty:</strong>
  <%= @item.warranty %>
</p>

<p>
  <strong>Date of purchase:</strong>
  <%= @item.date_of_purchase %>
</p>

<p>
  <strong>Length:</strong>
  <%= @item.length %>
</p>

<p>
  <strong>Width:</strong>
  <%= @item.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @item.height %>
</p>

<p>
  <strong>Amazon link:</strong>
  <%= @item.amazon_link %>
</p>

<p>
  <strong>Country:</strong>
  <%= @item.country %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @item.image.url(:medium) %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>